global:
  resolve_timeout: 5m
  smtp_from: <>
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_hello: localhost
  smtp_auth_username: <>
  smtp_auth_password: <>
  smtp_auth_identity: <>
  smtp_require_tls: true
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_match:
      severity: critical
    target_match_re:
      severity: warning|info
  - equal:
      - namespace
      - alertname
    source_match:
      severity: warning
    target_match_re:
      severity: info
receivers:
  - name: Default
    email_configs:
      - to: <>
        from: <>
  - name: My_filter
    email_configs:
      - to: <>
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - receiver: My_filter
      match_re:
        alertname: >-
          InstanceDown|TargetDown|ElasticsearchClusterNotHealthy|KubeDeploymentReplicasMismatch|KubeJobFailed|UpdateAvailable

